name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Restore Dependencies
        uses: bahmutov/npm-install@v1
        
      #- name: Fix Prettier
      #  run: yarn run prettier:fix

      #- name: Run Prettier
      #  run: yarn run prettier:check

      #- name: Run Embedme
      #  run: yarn run embedme:check

      - name: Publish to dev.to
        run: DEV_TO_GIT_TOKEN=${{ secrets.DEV_TO_GIT_TOKEN }} yarn run dev-to-git
